### ISSUE TITLE
Removing experimental data raises an error

### ISSUE THREAD

**Issue by mathijs-dumon** [PyXRD/PyXRD#16]
```
Traceback (most recent call last):
  File "PyXRD/mvc/adapters/gtk_support/treemodels/generic_tree_model.py", line 66, wrapped_func(*args=(<xy_list_store.XYListStore object at 0x7feecc5f5...emodels+xy_list_store+XYListStore at 0x10f5c7a0)>, <Gtk.TreeIter object at 0x7feecc582be8 (GtkTreeIter at 0x1411b8c0)>), **kargs={})
                try:
                    return func(*args, **kargs)
                except:
  variables: {'func': ('local', <function GenericTreeModel.do_unref_node at 0x7feeba032a60>), 'kargs': ('local', {}), 'args': ('local', (<xy_list_store.XYListStore object at 0x7feecc5f53f0 (mvc+adapters+gtk_support+treemodels+xy_list_store+XYListStore at 0x10f5c7a0)>, <Gtk.TreeIter object at 0x7feecc582be8 (GtkTreeIter at 0x1411b8c0)>))}
  File "PyXRD/mvc/adapters/gtk_support/treemodels/generic_tree_model.py", line 303, do_unref_node(self=<xy_list_store.XYListStore object at 0x7feecc5f5...emodels+xy_list_store+XYListStore at 0x10f5c7a0)>, iter=<Gtk.TreeIter object at 0x7feecc582be8 (GtkTreeIter at 0x1411b8c0)>)
        def do_unref_node(self, iter):
            self.on_unref_node(self.get_user_data(iter))
  variables: {'self.get_user_data': ('local', <bound method GenericTreeModel.get_user_data of <xy_list_store.XYListStore object at 0x7feecc5f53f0 (mvc+adapters+gtk_support+treemodels+xy_list_store+XYListStore at 0x10f5c7a0)>>), 'self.on_unref_node': ('local', <bound method GenericTreeModel.on_unref_node of <xy_list_store.XYListStore object at 0x7feecc5f53f0 (mvc+adapters+gtk_support+treemodels+xy_list_store+XYListStore at 0x10f5c7a0)>>), 'iter': ('local', <Gtk.TreeIter object at 0x7feecc582be8 (GtkTreeIter at 0x1411b8c0)>)}
  File "PyXRD/mvc/adapters/gtk_support/treemodels/generic_tree_model.py", line 162, get_user_data(self=<xy_list_store.XYListStore object at 0x7feecc5f5...emodels+xy_list_store+XYListStore at 0x10f5c7a0)>, iter=<Gtk.TreeIter object at 0x7feecc582be8 (GtkTreeIter at 0x1411b8c0)>)
            else:
                return _get_user_data_as_pyobject(iter)
  variables: {'_get_user_data_as_pyobject': ('global', <function _get_user_data_as_pyobject at 0x7feeba09e400>), 'iter': ('local', <Gtk.TreeIter object at 0x7feecc582be8 (GtkTreeIter at 0x1411b8c0)>)}
  File "PyXRD/mvc/adapters/gtk_support/treemodels/generic_tree_model.py", line 52, _get_user_data_as_pyobject(iter=<Gtk.TreeIter object at 0x7feecc582be8 (GtkTreeIter at 0x1411b8c0)>)
            citer = _CTreeIter.from_iter(iter)
            return ctypes.cast(citer.contents.user_data, ctypes.py_object).value
  variables: {'value': (None, []), 'citer.contents.user_data': ('local', <mvc.adapters.gtk_support.treemodels.generic_tree_model._CTreeIter object at 0x7feecbf837b8>), 'ctypes.py_object': ('global', <class 'ctypes.py_object'>), 'ctypes.cast': ('global', <function cast at 0x7feef160ad90>)}
ValueError: PyObject is NULL
```

**Comment by mathijs-dumon** [comment]
Fixed by 603c48e
